@Affiliate_InSprint_CommissionPage_CD @APUI_237_CD @CD
Feature: Affiliate V2.0 Commission feature for APUI237-CD


  @PhaseAll_CD @PhaseAll @APUI237_TC6_Aff_CD @Affiliates_Sprint15_CD @Acceptence_2_CD  @Affiliates_Regression_Suite_CD @Affiliates_RegressionRun
  Scenario Outline:TC6_APUI237_AFF To Verify last months statement is to be displayed by default when the user first opens the commissions page
    Given User launched application through "<browser>"
    And User navigate to Affiliate CD portal "<urlName>"
    When User enter UserName  "<UserName>" and password "<password>"and click login button
    Then User is navigated to Dashboard
    And User is able to view the Account Summary Section
    And User click on Commission tab on dashboard.
    Then User will be able to view the Summary report for Commission section
    And USer observe Your Commission Statement on Commissions page in bold
    Then User Observe the value of Statement Month under Your Commission Statement in bold letter
    Then User will be able to view the previous month of paid date into Statement month

    Examples:
      | browser | urlName        | UserName                | password    |
      | Chrome  | AffiliateCDURL | AffiliateCDUserName | AffPassword |

  @PhaseAll_CD @PhaseAll @APUI237_TC7_Aff_CD @Affiliates_Sprint15_CD @Acceptence_2_CD @Affiliates_Regression_Suite_CD @Affiliates_RegressionRun
  Scenario Outline:TC7_APUI237_AFF To Verify Paid Date under Your Commission Statement month section when user first opens the commissions page
    Given User launched application through "<browser>"
    And User navigate to Affiliate CD portal "<urlName>"
    When User enter UserName  "<UserName>" and password "<password>"and click login button
    Then User is navigated to Dashboard
    And User is able to view the Account Summary Section
    And User click on Commission tab on dashboard.
    Then User will be able to view the Summary report for Commission section
    And USer observe Your Commission Statement on Commissions page in bold
    Then User Observe the value of Statement Month under Your Commission Statement in bold letter
    Then User will be able to view the previous month of paid date into Statement month
    Then User will be able to view the fifth day of next month along with year

    Examples:
      | browser | urlName        | UserName                | password    |
      | Chrome  | AffiliateCDURL | AffiliateCDUserName | AffPassword |

  @PhaseAll_CD @PhaseAll @APUI237_TC12_Aff_CD @Affiliates_Sprint15_CD @Acceptence_4_CD @Affiliates_Regression_Suite_CD @Affiliates_RegressionRun @Smoke
  Scenario Outline:TC12_APUI237_AFF To Verify the Commission breakdown when generated option is been selected
    Given User launched application through "<browser>"
    And User navigate to Affiliate CD portal "<urlName>"
    When User enter UserName  "<UserName>" and password "<password>"and click login button
    Then User is navigated to Dashboard
    And User is able to view the Account Summary Section
    And User click on Commission tab on dashboard.
    And Use Clicks on Generated Radio Button
    Then User will be able to view the Summary report for Commission section
    And USer observe Your Commission Statement on Commissions page in bold
    Then User Observe the value of Statement Month under Your Commission Statement in bold letter
    And User Observe the commission payment breakdown options of the statement which is been Selected
    Then User will display the Client name and commission generated by him

    Examples:
      | browser | urlName        | UserName                              | password    |
      | Chrome  | AffiliateCDURL | AffiliateCDUserName_TestBusinessUser1 | AffPassword |

  @PhaseAll_CD @PhaseAll @APUI237_TC13_Aff_CD @Affiliates_Sprint15_CD @Acceptence_4_CD @Affiliates_Regression_Suite_CD @Affiliates_RegressionRun
  Scenario Outline:TC13_APUI237_AFF To Verify the Commission breakdown when paid option is been selected
    Given User launched application through "<browser>"
    And User navigate to Affiliate CD portal "<urlName>"
    When User enter UserName  "<UserName>" and password "<password>"and click login button
    Then User is navigated to Dashboard
    And User is able to view the Account Summary Section
    And User click on Commission tab on dashboard.
    And Use Clicks on Paid Radio Button
    Then User will be able to view the Summary report for Commission section
    And USer observe Your Commission Statement on Commissions page in bold
    Then User Observe the value of Statement Month under Your Commission Statement in bold letter
    And User Observe the commission payment breakdown options of the statement which is been Selected
    Then User will display the Client name and commission generated by him

    Examples:
      | browser | urlName        | UserName                              | password    |
      | Chrome  | AffiliateCDURL | AffiliateCDUserName_TestBusinessUser1 | AffPassword |

  @PhaseAll_CD @PhaseAll @APUI237_TC19_Aff_CD @Affiliates_Sprint15_CD @Acceptence_7_CD @Affiliates_Regression_Suite_CD @Affiliates_RegressionRun
  Scenario Outline:TC19_APUI237_AFF To Verify the download option to be displayed for payment breakdown commission Generted statement
    Given User launched application through "<browser>"
    And User navigate to Affiliate CD portal "<urlName>"
    When User enter UserName  "<UserName>" and password "<password>"and click login button
    Then User is navigated to Dashboard
    And User is able to view the Account Summary Section
    And User click on Commission tab on dashboard.
    And Use Clicks on Generated Radio Button
    Then User will be able to view the Summary report for Commission section
    And USer observe Your Commission Statement on Commissions page in bold
    Then User Observe the value of Statement Month under Your Commission Statement in bold letter
    And User Observe the commission payment breakdown options of the statement which is been Selected
    And User click on Download option
    Then User will be able to get two download option xlsx and pdf

    Examples:
      | browser | urlName        | UserName                              | password    |
      | Chrome  | AffiliateCDURL | AffiliateCDUserName_TestBusinessUser1 | AffPassword |

  @PhaseAll_CD @PhaseAll @APUI237_TC20_Aff_CD @Affiliates_Sprint15_CD @Acceptence_7_CD @Affiliates_Regression_Suite_CD @Affiliates_RegressionRun
  Scenario Outline:TC20_APUI237_AFF  To Verify the download option to be displayed for payment breakdown commission Generted statement
    Given User launched application through "<browser>"
    And User navigate to Affiliate CD portal "<urlName>"
    When User enter UserName  "<UserName>" and password "<password>"and click login button
    Then User is navigated to Dashboard
    And User is able to view the Account Summary Section
    And User click on Commission tab on dashboard.
    And Use Clicks on Paid Radio Button
    Then User will be able to view the Summary report for Commission section
    And USer observe Your Commission Statement on Commissions page in bold
    Then User Observe the value of Statement Month under Your Commission Statement in bold letter
    And User Observe the commission payment breakdown options of the statement which is been Selected
    And User click on Download option
    Then User will be able to get two download option xlsx and pdf

    Examples:
      | browser | urlName        | UserName                              | password    |
      | Chrome  | AffiliateCDURL | AffiliateCDUserName_TestBusinessUser1 | AffPassword |



